/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class DatabaseQueryJava {
  public static void hello() {
    DatabaseQueryJavaJNI.hello();
  }

  public static void printStr(String str) {
    DatabaseQueryJavaJNI.printStr(str);
  }

  public static String makeStr() {
    return DatabaseQueryJavaJNI.makeStr();
  }

  public static void takeStr(String str) {
    DatabaseQueryJavaJNI.takeStr(str);
  }

  public static void changeStr(String str, int length) {
    DatabaseQueryJavaJNI.changeStr(str, length);
  }

  public static void fillArray(SWIGTYPE_p_int arr, int n) {
    DatabaseQueryJavaJNI.fillArray(SWIGTYPE_p_int.getCPtr(arr), n);
  }

  public static void changeIntPointerArray(SWIGTYPE_p_int array, int n) {
    DatabaseQueryJavaJNI.changeIntPointerArray(SWIGTYPE_p_int.getCPtr(array), n);
  }

  public static void sleep(int sec) {
    DatabaseQueryJavaJNI.sleep(sec);
  }

  public static void startThreadAndCount(int n) {
    DatabaseQueryJavaJNI.startThreadAndCount(n);
  }

  public static SWIGTYPE_p_std__thread retCounterThread(int n) {
    long cPtr = DatabaseQueryJavaJNI.retCounterThread(n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__thread(cPtr, false);
  }

  public static void waitForThread(SWIGTYPE_p_std__thread t) {
    DatabaseQueryJavaJNI.waitForThread(SWIGTYPE_p_std__thread.getCPtr(t));
  }

}
