/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class DataRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DatabaseQueryJavaJNI.delete_DataRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    DatabaseQueryJavaJNI.DataRecord_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return DatabaseQueryJavaJNI.DataRecord_size_get(swigCPtr, this);
  }

  public void setTs(long value) {
    DatabaseQueryJavaJNI.DataRecord_ts_set(swigCPtr, this, value);
  }

  public long getTs() {
    return DatabaseQueryJavaJNI.DataRecord_ts_get(swigCPtr, this);
  }

  public void setAs(long value) {
    DatabaseQueryJavaJNI.DataRecord_as_set(swigCPtr, this, value);
  }

  public long getAs() {
    return DatabaseQueryJavaJNI.DataRecord_as_get(swigCPtr, this);
  }

  public void setCs(long value) {
    DatabaseQueryJavaJNI.DataRecord_cs_set(swigCPtr, this, value);
  }

  public long getCs() {
    return DatabaseQueryJavaJNI.DataRecord_cs_get(swigCPtr, this);
  }

  public void setDs(long value) {
    DatabaseQueryJavaJNI.DataRecord_ds_set(swigCPtr, this, value);
  }

  public long getDs() {
    return DatabaseQueryJavaJNI.DataRecord_ds_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    DatabaseQueryJavaJNI.DataRecord_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return DatabaseQueryJavaJNI.DataRecord_title_get(swigCPtr, this);
  }

  public void set_abstract(String value) {
    DatabaseQueryJavaJNI.DataRecord__abstract_set(swigCPtr, this, value);
  }

  public String get_abstract() {
    return DatabaseQueryJavaJNI.DataRecord__abstract_get(swigCPtr, this);
  }

  public void setClaim(String value) {
    DatabaseQueryJavaJNI.DataRecord_claim_set(swigCPtr, this, value);
  }

  public String getClaim() {
    return DatabaseQueryJavaJNI.DataRecord_claim_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    DatabaseQueryJavaJNI.DataRecord_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return DatabaseQueryJavaJNI.DataRecord_description_get(swigCPtr, this);
  }

  public DataRecord() {
    this(DatabaseQueryJavaJNI.new_DataRecord__SWIG_0(), true);
  }

  public DataRecord(long _size, long _ts, long _as, long _cs, long _ds, String _title, String _abstract, String _claim, String _description) {
    this(DatabaseQueryJavaJNI.new_DataRecord__SWIG_1(_size, _ts, _as, _cs, _ds, _title, _abstract, _claim, _description), true);
  }

  public DataRecord(DataRecord other) {
    this(DatabaseQueryJavaJNI.new_DataRecord__SWIG_2(DataRecord.getCPtr(other), other), true);
  }

  public String stringify() {
    return DatabaseQueryJavaJNI.DataRecord_stringify(swigCPtr, this);
  }

}
