/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class DatabaseQueryManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DatabaseQueryManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DatabaseQueryManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DatabaseQueryJavaJNI.delete_DatabaseQueryManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DatabaseQueryManager(String indexFilename, String dataPath, String dataFilePrefix) {
    this(DatabaseQueryJavaJNI.new_DatabaseQueryManager__SWIG_0(indexFilename, dataPath, dataFilePrefix), true);
  }

  public DatabaseQueryManager(String indexFilename, String dataPath) {
    this(DatabaseQueryJavaJNI.new_DatabaseQueryManager__SWIG_1(indexFilename, dataPath), true);
  }

  public String getBinFilenameWithBinId(long binId) {
    return DatabaseQueryJavaJNI.DatabaseQueryManager_getBinFilenameWithBinId(swigCPtr, this, binId);
  }

  public IndexValue getInfoById(String id) {
    long cPtr = DatabaseQueryJavaJNI.DatabaseQueryManager_getInfoById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new IndexValue(cPtr, false);
  }

  public void getInfoByIdList(StringVector idList, SWIGTYPE_p_std__vectorT_IndexValue_const_p_t output) {
    DatabaseQueryJavaJNI.DatabaseQueryManager_getInfoByIdList(swigCPtr, this, StringVector.getCPtr(idList), idList, SWIGTYPE_p_std__vectorT_IndexValue_const_p_t.getCPtr(output));
  }

  public void getAllId(StringVector pidList, StringVector aidList) {
    DatabaseQueryJavaJNI.DatabaseQueryManager_getAllId__SWIG_0(swigCPtr, this, StringVector.getCPtr(pidList), pidList, StringVector.getCPtr(aidList), aidList);
  }

  public void getAllId(StringVector pidList) {
    DatabaseQueryJavaJNI.DatabaseQueryManager_getAllId__SWIG_1(swigCPtr, this, StringVector.getCPtr(pidList), pidList);
  }

  public void getAllId() {
    DatabaseQueryJavaJNI.DatabaseQueryManager_getAllId__SWIG_2(swigCPtr, this);
  }

  public boolean getContentById(String id, DataRecord dataRecord) {
    return DatabaseQueryJavaJNI.DatabaseQueryManager_getContentById(swigCPtr, this, id, DataRecord.getCPtr(dataRecord), dataRecord);
  }

  public void getContentByIdList(StringVector idList, IdDataRecordVector idDataRecordList) {
    DatabaseQueryJavaJNI.DatabaseQueryManager_getContentByIdList(swigCPtr, this, StringVector.getCPtr(idList), idList, IdDataRecordVector.getCPtr(idDataRecordList), idDataRecordList);
  }

}
