/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class IdDataRecord {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IdDataRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdDataRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DatabaseQueryJavaJNI.delete_IdDataRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPid(String value) {
    DatabaseQueryJavaJNI.IdDataRecord_pid_set(swigCPtr, this, value);
  }

  public String getPid() {
    return DatabaseQueryJavaJNI.IdDataRecord_pid_get(swigCPtr, this);
  }

  public void setAid(String value) {
    DatabaseQueryJavaJNI.IdDataRecord_aid_set(swigCPtr, this, value);
  }

  public String getAid() {
    return DatabaseQueryJavaJNI.IdDataRecord_aid_get(swigCPtr, this);
  }

  public DataRecord getDataRecord() {
    long cPtr = DatabaseQueryJavaJNI.IdDataRecord_dataRecord_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DataRecord(cPtr, false);
  }

  public IdDataRecord() {
    this(DatabaseQueryJavaJNI.new_IdDataRecord(), true);
  }

}
