/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class IndexValue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IndexValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DatabaseQueryJavaJNI.delete_IndexValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getPid() {
    return DatabaseQueryJavaJNI.IndexValue_pid_get(swigCPtr, this);
  }

  public String getAid() {
    return DatabaseQueryJavaJNI.IndexValue_aid_get(swigCPtr, this);
  }

  public String getAppDate() {
    return DatabaseQueryJavaJNI.IndexValue_appDate_get(swigCPtr, this);
  }

  public String getIpc() {
    return DatabaseQueryJavaJNI.IndexValue_ipc_get(swigCPtr, this);
  }

  public long getBinId() {
    return DatabaseQueryJavaJNI.IndexValue_binId_get(swigCPtr, this);
  }

  public long getTi() {
    return DatabaseQueryJavaJNI.IndexValue_ti_get(swigCPtr, this);
  }

  public long getAi() {
    return DatabaseQueryJavaJNI.IndexValue_ai_get(swigCPtr, this);
  }

  public long getCi() {
    return DatabaseQueryJavaJNI.IndexValue_ci_get(swigCPtr, this);
  }

  public long getDi() {
    return DatabaseQueryJavaJNI.IndexValue_di_get(swigCPtr, this);
  }

  public long getOffset() {
    return DatabaseQueryJavaJNI.IndexValue_offset_get(swigCPtr, this);
  }

  public String stringify() {
    return DatabaseQueryJavaJNI.IndexValue_stringify(swigCPtr, this);
  }

  public IndexValue() {
    this(DatabaseQueryJavaJNI.new_IndexValue(), true);
  }

  public final static String header = DatabaseQueryJavaJNI.IndexValue_header_get();
}
