/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class IndexValueVector extends java.util.AbstractList<IndexValue> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IndexValueVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexValueVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DatabaseQueryJavaJNI.delete_IndexValueVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexValueVector(IndexValue[] initialElements) {
    this();
    for (IndexValue element : initialElements) {
      add(element);
    }
  }

  public IndexValueVector(Iterable<IndexValue> initialElements) {
    this();
    for (IndexValue element : initialElements) {
      add(element);
    }
  }

  public IndexValue get(int index) {
    return doGet(index);
  }

  public IndexValue set(int index, IndexValue e) {
    return doSet(index, e);
  }

  public boolean add(IndexValue e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, IndexValue e) {
    modCount++;
    doAdd(index, e);
  }

  public IndexValue remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public IndexValueVector() {
    this(DatabaseQueryJavaJNI.new_IndexValueVector__SWIG_0(), true);
  }

  public IndexValueVector(IndexValueVector other) {
    this(DatabaseQueryJavaJNI.new_IndexValueVector__SWIG_1(IndexValueVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return DatabaseQueryJavaJNI.IndexValueVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    DatabaseQueryJavaJNI.IndexValueVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return DatabaseQueryJavaJNI.IndexValueVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    DatabaseQueryJavaJNI.IndexValueVector_clear(swigCPtr, this);
  }

  public IndexValueVector(int count, IndexValue value) {
    this(DatabaseQueryJavaJNI.new_IndexValueVector__SWIG_2(count, IndexValue.getCPtr(value), value), true);
  }

  private int doSize() {
    return DatabaseQueryJavaJNI.IndexValueVector_doSize(swigCPtr, this);
  }

  private void doAdd(IndexValue x) {
    DatabaseQueryJavaJNI.IndexValueVector_doAdd__SWIG_0(swigCPtr, this, IndexValue.getCPtr(x), x);
  }

  private void doAdd(int index, IndexValue x) {
    DatabaseQueryJavaJNI.IndexValueVector_doAdd__SWIG_1(swigCPtr, this, index, IndexValue.getCPtr(x), x);
  }

  private IndexValue doRemove(int index) {
    long cPtr = DatabaseQueryJavaJNI.IndexValueVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IndexValue(cPtr, false);
  }

  private IndexValue doGet(int index) {
    long cPtr = DatabaseQueryJavaJNI.IndexValueVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IndexValue(cPtr, false);
  }

  private IndexValue doSet(int index, IndexValue val) {
    long cPtr = DatabaseQueryJavaJNI.IndexValueVector_doSet(swigCPtr, this, index, IndexValue.getCPtr(val), val);
    return (cPtr == 0) ? null : new IndexValue(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    DatabaseQueryJavaJNI.IndexValueVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
