/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class PairII {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PairII(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PairII obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DatabaseQueryJavaJNI.delete_PairII(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFirst(int value) {
    DatabaseQueryJavaJNI.PairII_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return DatabaseQueryJavaJNI.PairII_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    DatabaseQueryJavaJNI.PairII_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return DatabaseQueryJavaJNI.PairII_second_get(swigCPtr, this);
  }

  public PairII() {
    this(DatabaseQueryJavaJNI.new_PairII(), true);
  }

}
