/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DatabaseQuery;

public class SWIGTYPE_p_std__thread {
  private transient long swigCPtr;

  protected SWIGTYPE_p_std__thread(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__thread() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_std__thread obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

